version: '3.9'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres05
      POSTGRES_DB: ecommerce
    ports:
      - "5432:5436"
    networks:
      - app_network
  web:
    build:
      context: .
      dockerfile: Dockerfile

    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgres://postgres:postgres05@db:5432/ecommerce
      - SECRET_KEY=o4eiQ8p2lXpMMj5dCeVGzlD_sY0mbGDfFYiew-ZaLAU=
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - app_network
networks:
  app_network:
    driver: bridge
